const { expect, test } = require('@playwright/test');

async function openRouteFromHome(page, href) {
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'VxFormGenerator Demo' })).toBeVisible();
  await page.locator('.card').filter({ has: page.locator(`a[href="${href}"]`) }).getByRole('link').click();
}

async function navigateClientSide(page, href) {
  await page.evaluate(path => {
    history.pushState(null, '', `/${path}`);
    window.dispatchEvent(new PopStateEvent('popstate'));
  }, href);
}

test('demo routes validate generated forms and custom templates', async ({ page }) => {
  await page.goto('/');

  await expect(page.getByRole('heading', { name: 'VxFormGenerator Demo' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Model based form' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Dynamic metadata form' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Custom field template' })).toBeVisible();

  await page.locator('.card').filter({ has: page.locator('a[href="definition-form"]') }).getByRole('link').click();

  await expect(page.getByRole('heading', { name: 'Model Based Form Demo' })).toBeVisible();

  const optionsCard = page.locator('.card').filter({ hasText: 'Change form options' });
  await optionsCard.locator('select').first().selectOption({ label: 'Advanced datastructure' });
  await optionsCard.getByRole('button', { name: 'Submit' }).click();

  const generatedCard = page.locator('.card').filter({ hasText: 'Generated by POCO' });
  await expect(generatedCard).toBeVisible();
  await expect(generatedCard.locator('.vx-form-left-row-label:not(.vx-form-explicit-row-label)', { hasText: /Firstname|Voornaam/ })).toBeVisible();

  await expect(generatedCard.locator('.vx-form-left-field-label', { hasText: /Firstname|Voornaam/ })).toBeVisible();
  await expect(generatedCard.locator('.vx-form-left-field-label', { hasText: 'Lastname' })).toBeVisible();

  const explicitAddressLabel = generatedCard.locator('.vx-form-explicit-row-label', { hasText: 'Adress' });
  await expect(explicitAddressLabel).toBeVisible();
  await expect(generatedCard.locator('.vx-form-left-field-label', { hasText: 'Street' })).toHaveCount(0);
  await expect(generatedCard.locator('.vx-form-left-field-label', { hasText: 'Number' })).toHaveCount(0);

  await navigateClientSide(page, 'dynamic-form');

  await expect(page.getByRole('heading', { name: 'Dynamic Metadata Form Demo' })).toBeVisible();
  await expect(page.getByText('Name: String')).toBeVisible();
  await expect(page.getByText('FeedingSessionForm')).toBeVisible();

  await page.getByPlaceholder('Session name').fill('Evening feed');
  await expect(page.getByPlaceholder('Session name')).toHaveValue('Evening feed');

  await navigateClientSide(page, 'custom-field-template');

  await expect(page.getByRole('heading', { name: 'Custom Field Template Demo' })).toBeVisible();

  const surnameField = page.locator('[data-field-name="SurName"]');
  await expect(surnameField.locator('label')).toHaveText(/Firstname|Voornaam/);
  await surnameField.locator('input').fill('Template value');
  await expect(surnameField.locator('input')).toHaveValue('Template value');
});

test('model based form stacks left-oriented columns on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });

  await openRouteFromHome(page, 'definition-form');

  const optionsCard = page.locator('.card').filter({ hasText: 'Change form options' });
  await optionsCard.locator('select').first().selectOption({ label: 'Advanced datastructure' });
  await optionsCard.getByRole('button', { name: 'Submit' }).click();

  const generatedCard = page.locator('.card').filter({ hasText: 'Generated by POCO' });
  await expect(generatedCard).toBeVisible();
  const firstColumn = generatedCard.locator('.vx-form-left-column').first();
  const box = await firstColumn.boundingBox();

  expect(box).not.toBeNull();
  expect(box.width).toBeGreaterThan(300);
});
