name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      continue-on-error: true
      env:
       NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push "**/VxFormGenerator.*.nupkg" -k ${{env.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
      
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
